# Generated by Django 3.2.6 on 2021-08-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author_book'),
    ]

    operations = [
    ]
