# Generated by Django 3.2.6 on 2021-08-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210816_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.URLField(default='null', max_length=250),
            preserve_default=False,
        ),
    ]
