# Generated by Django 3.2.6 on 2021-08-17 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_rename_authors_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
    ]
