# Generated by Django 3.2.6 on 2021-08-17 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_rename_author_book_authors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
    ]
